### PR TITLE
Only re-open executable as O_RDWR if .ape present

### LINKED ISSUE #233: redbean crashes with SIGSEGV under AWS Lambda
When attempting to run [a redbean executable with the .ape header removed](https://github.com/kissgyorgy/redbean-docker) in AWS Lambda via Docker image, redbean will crash with a SIGSEGV:

```
Segmentation fault      (core dumped) redbean.com -vvvmbagD .
```

The core dump yields the following backtrace:
```
#0  __oncrash_sigsegv () at libc/log/oncrashthunks.S:57
#1  <signal handler called>
#2  OpenExecutable () at libc/runtime/openexecutable.S:172
#3  0x000000000040f802 in RestoreApe () at tool/net/redbean.c:5579
#4  0x000000000041b6d3 in RedBean (argc=argc@entry=3, argv=0x7fc07c5e5000, argv@entry=0x7fff6b268ec8) at tool/net/redbean.c:5674
#5  0x000000000041bc02 in main (argc=3, argv=0x7fff6b268ec8) at tool/net/redbean.c:5751
```

It appears that the remapping of the executable as O_RDWR doesn't (currently) work under AWS Lambda.

### PR DESCRIPTION
**Pull request by rhencke**
This attempts to avoid a SIGSEGV in environments where the original
executable cannot be reopened as O_RDWR (AWS Lambda)

(hopefully) fixes #233

### CODE REVIEW

File: tool/net/redbean.c [hunk 1]
```diff
@@ -5035,7 +5035,6 @@ static int LuaGetComment(lua_State *L) {
   return 1;
 }
 
-
```
Comment (rhencke) [inline tool/net/redbean.c:5038]: `clang-format` wanted to do this.

File: tool/net/redbean.c [hunk 2]
```diff
@@ -6472,9 +6471,9 @@ static void RestoreApe(void) {
   if (IsOpenbsd()) return; /* TODO */
   if (IsNetbsd()) return;  /* TODO */
   if (endswith(zpath, ".com.dbg")) return;
-  close(zfd);
-  zfd = OpenExecutable();
   if ((a = GetAssetZip("/.ape", 5)) && (p = LoadAsset(a, &n))) {
+    close(zfd);
+    zfd = OpenExecutable();
```
Comment (rhencke) [inline tool/net/redbean.c:6476]: While this works for my use case (redbean starts successfully now for me with this change), I am concerned I might be breaking something else I'm not aware of.

**Review by jart — APPROVED** [review]
Thanks for noticing this. I'm not sure why the close logic was on the outside of that if statement.

Thank you for running clang-format.
